name: Build PDF using typst

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build euler-lagrange.pdf with Typst
      uses: lvignoli/typst-action@v0
      with:
        source_file: euler-lagrange.typ
    - name: Build euler-lagrange-jp.pdf with Typst
      uses: lvignoli/typst-action@v0
      with:
        source_file: euler-lagrange-jp.typ
    - name: Build neural-network.pdf with Typst
      uses: lvignoli/typst-action@v0
      with:
        source_file: neural-network.typ

    - name: Upload Euler-Lagrange PDF file
      uses: actions/upload-artifact@v3
      with:
        name: Euler-Lagrange PDF
        path: euler-lagrange.pdf
    - name: Upload Euler-Lagrange JP PDF file
      uses: actions/upload-artifact@v3
      with:
        name: Euler-Lagrange JP PDF
        path: euler-lagrange-jp.pdf
    - name: Upload Neural network PDF file
      uses: actions/upload-artifact@v3
      with:
        name: Neural network PDF
        path: neural-network.pdf

    - run: mkdir output && cp *.pdf output/

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        force_orphan: true
