name: Build PDF using typst

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Typst
      uses: lvignoli/typst-action@v0
      with:
        source_file: euler-lagrange.typ
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: euler-lagrange.pdf

    - run: mkdir output && cp euler-lagrange.pdf output/

    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        force_orphan: true
